StackName: "gc-guardrails"
GitSourceVersion: "1.00"
AWS_REGION: "ca-central-1"
PipelineBucket: ""
EnvironmentName: "cds"
SSC_AWS_SERVER: ""
CACVersion: "2.0.4"
Parameters:
  OrganizationName: "CDS"
  OrganizationId: ""
  RootOUID: ""
  AuditAccountID: ""
  SecurityOUID: ""
  # Can be left default
  RolePrefix: "gc-"
  AccelRolePrefix: "LZ-"
  AcceleratorRole: "OrganizationAccountAccessRole"
  DestBucketName: ""
  EvidenceBucketName: ""
  AWSConfigConformsBucketName: ""
  AdditionalAssessmentAdminRoleARN: ""
  ExecutionName: "gc-fedclient-execution-role"
  DeployRoles: "true"
  BGA1: "Breakglass user 1"
  BGA2: "Breakglass user 2"
