StackName: "ssc-gc-guardrails"
GitSourceVersion: "1.00"
AWS_REGION: "ca-central-1"
PipelineBucket: ""
EnvironmentName: "ssc-cac"
SSC_AWS_SERVER: ""
CACVersion: "1.0.0"
Parameters:
  OrganizationName: "CDS"
  OrganizationId: ""
  RootOUID: ""
  AuditAccountID: ""
  SecurityOUID: ""
  # Can be left default
  RolePrefix: "gc-"
  AccelRolePrefix: "LZ-"
  AcceleratorRole: "OrganizationAccountAccessRole"
  DestBucketName: ""
  EvidenceBucketName: ""
  AWSConfigConformsBucketName: ""
  AdditionalAssessmentAdminRoleARN: ""
  ExecutionName: "gc-fedclient-execution-role"
  DeployRoles: "true"
  BGA1: "put in names of breakglass account 1"
  BGA2: "put in names of breakglass account 2"
